### ISSUE TITLE
Eliminar componente Slider de Home 

### ISSUE THREAD

**Issue by Franzcod** [alkemyTech/OT139-CLIENT#38]
El componente Slider que está en Home no corresponde. 

Tarea: Eliminar el componente Slider de Home y la constante 'dataSlide'

**Comment by Franzcod** [comment]
Y la constante 'dataSlide'

**Comment by lrlichardi** [comment]
Mover de component/home/home.module.css a views/home

**Comment by YonPalac1** [comment]
El link de la imagen que está en el endpoint de organization lleva a la carpeta de la imagen, pero no a la imagen en si:
Cambiar por:
https://lh4.googleusercontent.com/8d2ci9rICYB3X3es_CKLJPtRugK-Mi-ThEqcSVYBqFJLj0nAwv0kJharSZLWl24X4Y-KAYQ3MWqdJw=w1366-h643
