### ISSUE TITLE
Agregar manejo de layouts

### ISSUE THREAD

**Issue by Galaeno** [alkemyTech/OT139-CLIENT#43]
Al crearse la tarea 35 creando el layout de backoffice, se dio lugar a tener la posibilidad de manejar layouts. En ningun tarea se especifica éste manejo. El issue plantea crear éste mismo, permitiendo que el usuario adminsitrador pueda ver el layout de backoffice, el usuario logeado el layout de usuario y alguien sin logearse, vea el layout publico/base

**Comment by AndresHense** [comment]
gonzalo sabes alguna forma de hacer que un wrapper sea condicional?, estuve viendo de como implementar esto y se me ocurrio hacer esto en el index.js

```javascript
return <>{!user ?<Unlogged><App/><Unlogged/>
: user.isAdmin ? <Backoffice><App/><Backoffice/>
: <Logged><App/><Logged/>}
</>
```
pero se me hace que me estoy repitiendo mucho, no hay una forma de usar alguna especie de condicional que me deje llamar una sola vez a App, algo como esto

```javascript
return <bool? ...>
   <App/>
<.../>
```
